services:
  mysql:
    image: mysql:8.0
    container_name: enlighten-mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: enlighten-platform-web/Dockerfile
      network: host
    image: enlighten-platform-web:${APP_VERSION}
    container_name: enlighten-app
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=${JAVA_OPTS}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_UPSTREAM_FILL_IN_URL=${APP_UPSTREAM_FILL_IN_URL}
      - APP_UPSTREAM_SCIENCE_GENERATOR_URL=${APP_UPSTREAM_SCIENCE_GENERATOR_URL}
      - APP_UPSTREAM_CONVERT2MEDIA_URL=${APP_UPSTREAM_CONVERT2MEDIA_URL}
      - APP_UPSTREAM_CONVERT2GZH_RE_URL=${APP_UPSTREAM_CONVERT2GZH_RE_URL}
      - APP_UPSTREAM_CONVERT2GZH_URL=${APP_UPSTREAM_CONVERT2GZH_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    ports:
      - "${APP_PORT}:8080"
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
  redis:
    image: redis:7
    container_name: enlighten-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    container_name: enlighten-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=Asia/Shanghai
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    name: enlighten-net


