services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: enlighten-dev
    volumes:
      - ..:/workspace:cached
      - m2:/root/.m2
    working_dir: /workspace
    env_file:
      - ../.env
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
      - ROCKETMQ_NAME_SERVER=${ROCKETMQ_NAME_SERVER}
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - default

volumes:
  m2:


