name: CI Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven (skip tests)
        run: mvn -q -B -DskipTests clean package

      - name: Show built artifacts
        run: |
          ls -al enlighten-platform-web/target || true
          ls -al enlighten-platform-biz/target || true
          ls -al enlighten-platform-api/target || true

name: CI Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven (skip tests)
        run: mvn -q -B -DskipTests clean package

      - name: Show built artifacts
        run: |
          ls -al enlighten-platform-web/target || true
          ls -al enlighten-platform-biz/target || true
          ls -al enlighten-platform-api/target || true


